# Generated by Django 5.2.4 on 2025-07-18 09:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-transaction_date"],
                "verbose_name": "거래",
                "verbose_name_plural": "거래 내역",
            },
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="account_id",
        ),
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="거래 계정",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account_details",
            field=models.CharField(
                help_text="예: 오픈뱅킹 출금, ATM 현금 입금, 올리브영 등",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="deposit_withdrawal_type",
            field=models.CharField(
                choices=[("deposit", "입금"), ("withdrawal", "출금")],
                help_text="입출금 여부",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="거래 일시"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("cash", "현금"),
                    ("transfer", "계좌 이체"),
                    ("auto_transfer", "자동 이체"),
                    ("card_payment", "카드 결제"),
                ],
                help_text="거래 유형",
                max_length=50,
            ),
        ),
    ]
