name: Checks

on:
  push:
    branches:
      - '**'  # 모든 브랜치
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      shell: bash

    - name: Add uv to PATH
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      shell: bash

    - name: Install Packages & Libraries with uv sync
      run: uv sync --dev
      shell: bash

    - name: Run isort (Import sorting)
      run: uv run isort . --check --diff
      shell: bash

    - name: Run black (Code formatting)
      run: uv run black . --check
      shell: bash

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p ${{ secrets.DB_PORT }} -U ${{ secrets.DB_USER }}; do
          sleep 1
        done
      shell: bash

    - name: Run Django Migration
      run: |
        uv run python manage.py makemigrations
        uv run python manage.py migrate
      shell: bash